### ISSUE TITLE
The roadmap on supporting more drones.

### ISSUE THREAD

**Issue by memory125** [dji-sdk/Windows-SDK#2]
Do you have a clear roadmap or supporting plan for more drones?

**Comment by mtreiber** [comment]
Agreed.  Will the M600 be supported?

**Comment by XietongLU** [comment]
We definitely will support more products and Mavic 2 series are the next. We don't have plan to support M600 yet.

**Comment by XietongLU** [comment]
@memory125 End of Dec or Jan next year.

**Comment by TimHsue** [comment]
And how about the Mavic Pro? Thanks!!

**Comment by memory125** [comment]
> @memory125 End of Dec or Jan next year.

Thanks
