### ISSUE TITLE
Unit and Coordinate system of SDK

### ISSUE THREAD

**Issue by zxwang96** [dji-sdk/Windows-SDK#22]
Hi, 
I was wondering the exact meaning of unit of latitude and  longitude used in this SDK. As I know, 1 degree is about 69 miles when we talk about geology, it will be unreasonable if we apply this unit. So I was wondering what does the degree here means, like 1 degree = ?. In addition, I also want to know the start point of the coordinate system. Is it a ego-centric coordinates system or it starts from where the drone taking off? Thanks!

**Comment by lanyusea** [comment]
>  it will be unreasonable if we apply this unit
it is float, which means the value you can set 0.0000001, 0.0000002, etc

> I also want to know the start point of the coordinate system. Is it a ego-centric coordinates system or it starts from where the drone taking off? Thanks!
not quite understand what you mean, if you're asking about the GPS coordinate, it should be the same as the regular definition.

**Comment by zxwang96** [comment]
> > it will be unreasonable if we apply this unit
> 
> it is float, which means the value you can set 0.0000001, 0.0000002, etc
> 
> > I also want to know the start point of the coordinate system. Is it a ego-centric coordinates system or it starts from where the drone taking off? Thanks!
> 
> not quite understand what you mean, if you're asking about the GPS coordinate, it should be the same as the regular definition.

Thanks Lanyusea. I got it, the CoordinateLocation2D is in geographical unit. So the issue I met is I want to control the drone to fly around in a in-door space, so I assume I need to do some low level control. Can you tell me what should I do? For instance:
`Waypoint waypoint = new Waypoint()
            {
                location = new LocationCoordinate2D() { latitude = latitude, longitude = longitude },
                altitude = 20,
                gimbalPitch = -30,
                turnMode = WaypointTurnMode.CLOCKWISE,
                heading = 0,
                actionRepeatTimes = 1,
                actionTimeoutInSeconds = 60,
                cornerRadiusInMeters = 0.2,
                speed = 0,
                shootPhotoTimeInterval = -1,
                shootPhotoDistanceInterval = -1,
                waypointActions = new List<WaypointAction>()
            };`

replace the location's LocationCoordinate2D() by DoublePoint2D?

**Comment by lanyusea** [comment]
> I assume I need to do some low level control.

yes

>an you tell me what should I do?

the waypoint here is not suitable for your requirement. Waypoint is designed for long-term outdoor flight task based on GPS.

For your requirement, I suggest use DJI Onboard SDK, which is designed for lowlevel control.

If you insist using Windows SDK, the https://developer.dji.com/api-reference/windows-api/VirtualRemoteController/VirtualRemoteController.html may help

**Comment by zxwang96** [comment]
Cool, thanks. I read the document you posted here. So I assume (-1, 1) corresponds to the maximum degree that the drone can perform. And the method ‘attitudechanged’ shows the range is (-180, 180), which I assume is unavailable to perform. So I was wondering the corresponding degree to (-1, 1). Btw, my drone is Mavic Air.
