### ISSUE TITLE
Can you provide SDK PDB files for debugging?

### ISSUE THREAD

**Issue by LiangJy123** [dji-sdk/Windows-SDK#39]
Because our app will crash.The SDK internal error was located through the dump file, but we don't have  its PDB file to find the problem exactly.

**Comment by dji-dev** [comment]
Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/30532'>Zendesk ticket #30532</a>:<br><br>Hi. You can provide us with the dump file and we will help you analyze the cause of the crash. You can feedback the crash to us by filling out the form(https://formcrafts.com/a/dji-developer-feedback-en).

**Comment by LiangJy123** [comment]
OK, Thank you.
I will update the SDK version to the latest.
If I meet the same problem, I will  take your advice.
