### ISSUE TITLE
publish visual inertial odometry output or publish current video feed and imu data

### ISSUE THREAD

**Issue by snakehaihai** [dji-sdk/Windows-SDK#4]
Can help publish the publish visual inertial odometry pose output 
or publish current video feed(15-30hz) and imu data(200-400hz) for running visual inertial odometry at PC side?

Regards
Shenghai Yuan

**Comment by XietongLU** [comment]
There is no way to get such high freq push data in Windows SDK. 
You can actually get the video feed (30 fps) and the attitude (10Hz).
