### ISSUE TITLE
Is the Mavic Mini a supported device?

### ISSUE THREAD

**Issue by sqltj** [dji-sdk/Windows-SDK#40]
Is the Mavic Mini a supported device?

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/30573'>Zendesk ticket #30573</a>:<br><br>The Mavic Mini is currently not supported by our SDK yet, but we will be providing support in a future release on the Mobile SDK.  Support through the Windows SDK is still being evaluated.

Lisa Fedane
DJI Developer Support

**Comment by jdagdelen** [comment]
I would love to see the windows sdk support the mini. It’s an interesting potential platform for off-payload machine learning applications.

**Comment by quocthinhvo** [comment]
I hope Mavic Mini support windows sdk
