### ISSUE TITLE
Connection Guide for DJI Mavic 2 Enterprise

### ISSUE THREAD

**Issue by ianhirsch** [dji-sdk/Windows-SDK#45]
I noticed on the latest release notes that the Mavic 2 Enterprise was now supported for the Windows SDK. Where can I find the USB authority configuration for this product?

**Comment by dji-dev** [comment]
Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/31974'>Zendesk ticket #31974</a>:<br><br>The config is the same as Mavic 2 pro/zoom. Please refer to this guide: https://developer.dji.com/cn/windows-sdk/documentation/connection/Mavic2.html.
