### ISSUE TITLE
No certificate found with the supplied thumbprint

### ISSUE THREAD

**Issue by wjsunny** [dji-sdk/Windows-SDK#47]
![image](https://user-images.githubusercontent.com/38364043/75551101-fbbebe80-5a65-11ea-8588-0956510800e7.png)

when I building DJISDKSample in VS studio 2019, I encounter error "No certificate found with the supplied thumbprint: 1284217E2639D5E6101420BF06002B38EBA72D32".
How should I fix this?

**Comment by dji-dev** [comment]
Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/32464'>Zendesk ticket #32464</a>:<br><br>Hi. Can you try again with visual studio 2017?

**Comment by wjsunny** [comment]
Hey, I tried with VS studio 2017. It works, but I think that why can't it run on VS studio 2019.
Thank you!
