### ISSUE TITLE
Mavic 2 enterprise video feed not working

### ISSUE THREAD

**Issue by walseb** [dji-sdk/Windows-SDK#49]
Hi! I'm trying to get a sample application working displaying a live video feed but none of the sample applications I have tried so far has worked. I have:
- updated both the drone (V01.01.0640) and the controller (V01.01.0410) to the latest version through `DJI Assistant 2 For Mavic`
- have the latest version of `windows-sdk` (0.3.2)
- completed all the steps of installing the correct usb drivers to the controller from [here](https://developer.dji.com/windows-sdk/documentation/connection/Mavic2.html)
- made sure to connect the controller through the micro-usb cable to the computer before turning the controller on but the live video still wont play. 
- I have read #32 and I'm not using the smart controller

This is how my device manager looks: 
![image](https://user-images.githubusercontent.com/2865774/78557972-17aa4280-7812-11ea-883b-93206a1ad5ea.png) Basic things like getting the name of the drone works fine: 
![image](https://user-images.githubusercontent.com/2865774/78558222-84bdd800-7812-11ea-889a-0ec4b3f66315.png) but the video stream wont work: 
![image](https://user-images.githubusercontent.com/2865774/78558340-acad3b80-7812-11ea-9beb-a7ab38b3ff11.png)
I got the sample application from [here](https://developer.dji.com/windows-sdk/documentation/quick-start/index.html)
I have also tried running both examples in [this](https://developer.dji.com/windows-sdk/documentation/tutorials/index.html) tutorial but it also had the same problem. Thanks for any help!

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/33361'>Zendesk ticket #33361</a>:<br><br>Dear Client
Thank you for contacting DJI.

It seems that your driver is not installed properly, you need to select the remote controller device and install the libusb-win32 to it. The device Manager List should be seen as this. WSDK is still on developing, documentations and APIs are still on beta. We strongly suggest you have a look at MSDK which is mature enough on the market. Sorry for your inconvience.
 ![](https://djisdksupport.zendesk.com/attachments/token/l03cPeAzeJqM3XNhWoBrKURsy/?name=inline1869408959.png)​​

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/l03cPeAzeJqM3XNhWoBrKURsy' target='zd_attach'>inline1869408959.png</a>

**Comment by walseb** [comment]
Seems like my problem was that I installed the `libusb-win32` driver instead of the `WinUSB` driver. It works fine now, thanks for the help!
