### ISSUE TITLE
Matrice 100 Compatibility

### ISSUE THREAD

**Issue by Asendo316** [dji-sdk/Windows-SDK#62]
Is the SDK Compatible with DJI Matrice 100?

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40963'>Zendesk ticket #40963</a>:<br><br>Dear Client
Thank you for contacting DJI.

No, only Mobile SDK supports Matrice 100.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
