### ISSUE TITLE
Error Compiling Code 

### ISSUE THREAD

**Issue by Asendo316** [dji-sdk/Windows-SDK#63]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'pthread.h': No such file or directory (compiling source file videoparser.cpp)	DJIVideoParser	D:\User\RAW\Windows-SDK-master\Windows-SDK-master\Sample Code\DJIVideoParser\Queue.h	5	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'pthread.h': No such file or directory (compiling source file videoparsermgr.cpp)	DJIVideoParser	D:\User\RAW\Windows-SDK-master\Windows-SDK-master\Sample Code\DJIVideoParser\Queue.h	5	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'pthread.h': No such file or directory (compiling source file VideoWrapper.cpp)	
DJIVideoParser	D:\User\RAW\Windows-SDK-master\Windows-SDK-master\Sample Code\DJIVideoParser\Queue.h	5

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40966'>Zendesk ticket #40966</a>:<br><br>Dear Client
Thank you for contacting DJI.

Make sure you mee the requirement.
1. Windows 10 (version 1803 or higher)
2. Visual Studio 2017 with Windows 10 SDK 16299 and 17134.
3. Use debug-x86 mode to compile and run in Visual Studio 2017.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by Asendo316** [comment]
Hello, 

My environment meets the requirement.

It appears the pthread and all the other major ffmpeg libraries are missing from solution

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'libavcodec/avcodec.h': No such file or directory (compiling source file Parser.cpp)	D:\User\RAW\Windows-SDK-master\Windows-SDK-master\Sample Code\DJIVideoParser\Queue.h	

What to do?

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40966'>Zendesk ticket #40966</a>:<br><br>Dear Client
Thank you for contacting DJI.

That seems weird because I can comple and run the project and we haven't update the project for a long time. Maybe try this step? It seems like the 3rd party library hasn't been included.
 ![](https://djisdksupport.zendesk.com/attachments/token/zgf9zbCvxJ9V5d6BMsask2cLU/?name=inline-1441214494.png)

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by Asendo316** [comment]
Hello Thanks for your prompt response.

I cant find the libcrypto-1_1.dll library anywhere in the cloned project please.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40966'>Zendesk ticket #40966</a>:<br><br>Dear Client
Thank you for contacting DJI.

This is the default settings I have downloaded from github, maybe look at the right hand side to see if and dll is missing from your side. Maybe redownload the project again.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support ![](https://djisdksupport.zendesk.com/attachments/token/PIwGPOGRt0nGlhr2IFiGXv7qH/?name=inline-959032929.png)​

 ![](https://djisdksupport.zendesk.com/attachments/token/6HA3AICMflBwqjfGj5WQTSErX/?name=inline1871848265.png)​<br><a href='https://djisdksupport.zendesk.com/attachments/token/PIwGPOGRt0nGlhr2IFiGXv7qH' target='zd_attach'>inline-959032929.png</a><br><a href='https://djisdksupport.zendesk.com/attachments/token/6HA3AICMflBwqjfGj5WQTSErX' target='zd_attach'>inline1871848265.png</a>

**Comment by Asendo316** [comment]
I have been able to run the code after a fresh pull from he repository thanks
